/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author jhose
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelPrincipal = new javax.swing.JPanel();
        GymManagerPro = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        menuEntrenadores = new javax.swing.JMenu();
        itemEntrenadores = new javax.swing.JMenuItem();
        menuMembresias = new javax.swing.JMenu();
        itemMembresias = new javax.swing.JMenuItem();
        menuPagos = new javax.swing.JMenu();
        itemRegistrarPago = new javax.swing.JMenuItem();
        itemHistorialPagos = new javax.swing.JMenuItem();
        menuAsistencias = new javax.swing.JMenu();
        itemRegistrarAsistencia = new javax.swing.JMenuItem();
        itemHistorialAsistenica = new javax.swing.JMenuItem();
        menuRutinas = new javax.swing.JMenu();
        itemRutinas = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemUsuarios = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReporteClientes = new javax.swing.JMenuItem();
        itemReportePagos = new javax.swing.JMenuItem();
        itemReporteAsistencias = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymManagerPro");
        setMaximumSize(new java.awt.Dimension(680, 370));
        setMinimumSize(new java.awt.Dimension(680, 370));
        setPreferredSize(new java.awt.Dimension(680, 370));
        setResizable(false);

        panelPrincipal.setMaximumSize(new java.awt.Dimension(680, 347));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(680, 347));
        panelPrincipal.setName(""); // NOI18N

        GymManagerPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sistema de Gestión para Gimnasios LOGo.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(GymManagerPro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addGap(118, 118, 118))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GymManagerPro)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblUsuario)))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");

        itemCerrarSesion.setText("Cerrar Sesión");
        menuArchivo.add(itemCerrarSesion);

        itemSalir.setText("Salir");
        menuArchivo.add(itemSalir);

        menuPrincipal.add(menuArchivo);

        menuClientes.setText("Clientes");

        itemClientes.setText("Gestionar Clientes");
        menuClientes.add(itemClientes);

        menuPrincipal.add(menuClientes);

        menuEntrenadores.setText("Entrenadores");

        itemEntrenadores.setText("Gestionar Entrenadores");
        menuEntrenadores.add(itemEntrenadores);

        menuPrincipal.add(menuEntrenadores);

        menuMembresias.setText("Membresías");

        itemMembresias.setText("Gestionar Membresias");
        menuMembresias.add(itemMembresias);

        menuPrincipal.add(menuMembresias);

        menuPagos.setText("Pagos");

        itemRegistrarPago.setText("Registrar Pago");
        menuPagos.add(itemRegistrarPago);

        itemHistorialPagos.setText("Historial Pagos");
        menuPagos.add(itemHistorialPagos);

        menuPrincipal.add(menuPagos);

        menuAsistencias.setText("Asistencias");

        itemRegistrarAsistencia.setText("Registrar Asistencia");
        menuAsistencias.add(itemRegistrarAsistencia);

        itemHistorialAsistenica.setText("Historial de Asistencia");
        menuAsistencias.add(itemHistorialAsistenica);

        menuPrincipal.add(menuAsistencias);

        menuRutinas.setText("Rutinas");

        itemRutinas.setText("Gestionar Rutinas");
        itemRutinas.addActionListener(this::itemRutinasActionPerformed);
        menuRutinas.add(itemRutinas);

        menuPrincipal.add(menuRutinas);

        menuUsuarios.setText("Usuarios");

        itemUsuarios.setText("Gestionar Usuarios");
        menuUsuarios.add(itemUsuarios);

        menuPrincipal.add(menuUsuarios);

        menuReportes.setText("Reportes");

        itemReporteClientes.setText("Reporte Clientes");
        menuReportes.add(itemReporteClientes);

        itemReportePagos.setText("Reporte Pagos");
        menuReportes.add(itemReportePagos);

        itemReporteAsistencias.setText("Reporte Asistencias");
        menuReportes.add(itemReporteAsistencias);

        menuPrincipal.add(menuReportes);

        menuAyuda.setText("Ayuda");

        itemAcerca.setText("Acerca del Sistema");
        menuAyuda.add(itemAcerca);

        menuPrincipal.add(menuAyuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRutinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRutinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GymManagerPro;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemEntrenadores;
    private javax.swing.JMenuItem itemHistorialAsistenica;
    private javax.swing.JMenuItem itemHistorialPagos;
    private javax.swing.JMenuItem itemMembresias;
    private javax.swing.JMenuItem itemRegistrarAsistencia;
    private javax.swing.JMenuItem itemRegistrarPago;
    private javax.swing.JMenuItem itemReporteAsistencias;
    private javax.swing.JMenuItem itemReporteClientes;
    private javax.swing.JMenuItem itemReportePagos;
    private javax.swing.JMenuItem itemRutinas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAsistencias;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEntrenadores;
    private javax.swing.JMenu menuMembresias;
    private javax.swing.JMenu menuPagos;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuRutinas;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
